language: python
python:
  - 2.6
  - 2.7
  - pypy
services:
  - elasticsearch
install:
  - pip install -e .[testing]
  # Install the correct version of the elasticsearch lib for the version of
  # elasticsearch available on Travis (0.90.x)
  - pip install elasticsearch==0.4.5
script: nosetests
